name: CI

# Controls when the action will run. 
on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TASBE/TASBEFlowAnalytics-Tutorial
      - uses: actions/checkout@v2
        with:
      - uses: joergbrech/moxunit-action@master
        with:
          tests: tests
          src: code code/utils library_code library_code/jsonlab test_templates gmdistribution matlab_compat
          pkg: io
