name: CI

# Controls when the action will run. 
on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TASBE/TASBEFlowAnalytics-Tutorial
          path: TASBEFlowAnalytics-Tutorial
      - uses: actions/checkout@v2
        with:
          path: TASBEFlowAnalytics
      - name: Setup octave
        run: |
          sudo apt-get -y -qq install octave liboctave-dev
          cd /home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics/TASBEFlowAnalytics
          octave --no-gui --quiet --eval "pkg install matlab_compat/io-2.4.10.tar.gz"
          git clone https://github.com/MOxUnit/MOxUnit.git
          make -C MOxUnit install
      - name: Run tests
        run: |
          cd /home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics/TASBEFlowAnalytics
          make test          
