name: CI

# Controls when the action will run. 
on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TASBEFlowAnalytics
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TASBE/TASBEFlowAnalytics-Tutorial
          path: TASBEFlowAnalytics-Tutorial
      - uses: actions/checkout@v2
        with:
          path: TASBEFlowAnalytics
      - name: goto run directory
        run: |
          cd /home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics/TASBEFlowAnalytics-Tutorial
      - uses: joergbrech/moxunit-action@master
        with:
          tests: tests
          src: code code/utils library_code library_code/jsonlab test_templates gmdistribution matlab_compat
          pkg: io
